/* Copyright 2026 Alfa Financial Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.alfasoftware.soapstone;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Configuration bean for providing details of the security scheme in use so that the details can be included
 * in the OpenAPI document generated by Soapstone.
 * <p>
 * Soapstone currently only supports OAuth security schemes.
 * </p>
 */
public class SecurityConfiguration {

  /**
   * Enum for specifying the security scheme type.  Soapstone currently only supports OAuth security schemes.
   */
  public enum Type {
    APIKEY,
    HTTP,
    OAUTH2,
    OPENIDCONNECT,
    MUTUALTLS
  }

  /**
   * Enum for specifying the OAuth flow type for an OAuth security scheme
   */
  public enum OAuthFlowType {
    CLIENT_CREDENTIALS,
    PASSWORD,
    IMPLICIT,
    AUTH_CODE
  }

  private String securitySchemeName;
  private Type type;
  private Supplier<String> oauthTokenUrlSupplier;
  private OAuthFlowType oauthFlowType;
  private boolean granularScopes;
  private Function<String, String> transformPathToScope = s -> s.replace('/', '.').substring(1).toLowerCase(Locale.ROOT);
  private final Map<String, String> scopes = new HashMap<>();
  private final List<String> globalSecurityRequirementScopes = new ArrayList<>();

  public String getSecuritySchemeName() {
    return securitySchemeName;
  }

  public void setSecuritySchemeName(String securitySchemeName) {
    this.securitySchemeName = securitySchemeName;
  }

  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public String getOauthTokenUrl() {
    return oauthTokenUrlSupplier.get();
  }

  public void setOauthTokenUrlSupplier(Supplier<String> oauthTokenUrlSupplier) {
    this.oauthTokenUrlSupplier = oauthTokenUrlSupplier;
  }

  public OAuthFlowType getOauthFlowType() {
    return oauthFlowType;
  }

  public void setOauthFlowType(OAuthFlowType oauthFlowType) {
    this.oauthFlowType = oauthFlowType;
  }

  /**
   * Returns true if the API has been configured to use OAuth scopes at an operation level for granting access. i.e.
   * each individual method exposed on the API has its own scope
   */
  public boolean hasGranularScopes() {
    return granularScopes;
  }

  /**
   * Set whether the API has been configured to use OAuth scopes at an operation level for granting access. i.e.
   * each individual method exposed on the API has its own scope
   */
  public void setGranularScopes(boolean granularScopes) {
    this.granularScopes = granularScopes;
  }

  public Function<String, String> getTransformPathToScope() {
    return transformPathToScope;
  }

  /**
   * The default setting will convert to all lowercase, remove the leading '/' and replace the remaining '/' with '.'
   * <p>
   *   If set to null, the original path will be used as the scope
   * </p>
   */
  public void setTransformPathToScope(Function<String, String> transformPathToScope) {
    this.transformPathToScope = transformPathToScope;
  }

  public Map<String, String> getScopes() {
    return Map.copyOf(scopes);
  }

  public void addScope(String scope, String scopeDescription) {
    this.scopes.put(scope, scopeDescription);
  }

  public void addScopes(Map<String, String> scopes) {
    this.scopes.putAll(scopes);
  }

  public List<String> getGlobalSecurityRequirementScopes() {
    return globalSecurityRequirementScopes;
  }

  public void addGlobalSecurityRequirementScope(String scope) {
    this.globalSecurityRequirementScopes.add(scope);
  }
}
