package org.alfasoftware.soapstone;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Configuration bean for providing details of the security scheme in use so that the details can be included
 * in the OpenAPI document generated by Soapstone.
 * <p>
 * Soapstone currently only supports OAuth security schemes.
 * </p>
 */
public class SecurityConfiguration {

  /**
   * Enum for specifying the security scheme type.  Soapstone currently only supports OAuth security schemes.
   */
  public enum Type {
    APIKEY,
    HTTP,
    OAUTH2,
    OPENIDCONNECT,
    MUTUALTLS
  }

  /**
   * Enum for specifying the OAuth flow type for an OAuth security scheme
   */
  public enum OAuthFlowType {
    CLIENT_CREDENTIALS,
    PASSWORD,
    IMPLICIT,
    AUTH_CODE
  }

  private String securitySchemeName;
  private Type type;
  private String oauthTokenUrl;
  private OAuthFlowType oauthFlowType;
  private final Map<String, String> scopes = new HashMap<>();
  private final List<String> globalSecurityRequirementScopes = new ArrayList<>();

  public String getSecuritySchemeName() {
    return securitySchemeName;
  }

  public void setSecuritySchemeName(String securitySchemeName) {
    this.securitySchemeName = securitySchemeName;
  }

  public Type getType() {
    return type;
  }

  public void setType(Type type) {
    this.type = type;
  }

  public String getOauthTokenUrl() {
    return oauthTokenUrl;
  }

  public void setOauthTokenUrl(String oauthTokenUrl) {
    this.oauthTokenUrl = oauthTokenUrl;
  }

  public OAuthFlowType getOauthFlowType() {
    return oauthFlowType;
  }

  public void setOauthFlowType(OAuthFlowType oauthFlowType) {
    this.oauthFlowType = oauthFlowType;
  }

  public Map<String, String> getScopes() {
    return scopes;
  }

  public void addScope(String scope, String scopeDescription) {
    this.scopes.put(scope, scopeDescription);
  }

  public void addScopes(Map<String, String> scopes) {
    this.scopes.putAll(scopes);
  }

  public List<String> getGlobalSecurityRequirementScopes() {
    return globalSecurityRequirementScopes;
  }

  public void addGlobalSecurityRequirementScope(String scope) {
    this.globalSecurityRequirementScopes.add(scope);
  }
}
